#!/bin/bash
cd /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT


##===Capturing changed files from Gitlab into a variable====#
var=$(git diff --name-only $(cat /home/jenkins/Last_Commit_SHA_UAT) HEAD)

##===Initializing variable with current build logs==###
int=$JENKINS_HOME/jobs/$JOB_NAME/builds/$BUILD_NUMBER/log


#===Initializing variables for PLSQL objects to run in sequence===#
b=""
c=""
d=""
e=""
f=""
g=""
h=""



echo "var = $var"

#===Function to compile DB objects into Optima Databases==#
DBObjectscompile(){
echo "started executing $1 on DBs"

sqlplus /nolog <<EOF 
connect $OPTAU/$PWDOPTAU@OPTAU
select sysdate from dual;

set trimspool on
set serveroutput on
set pagesize 0
set long 20000000
set longchunksize 20000000
set linesize 32767


spool /home/jenkins/DBObjects_backup/APAC_Objects/bkpUAT_`date +%d%b%y`_$qtr.sql;
SELECT dbms_metadata.get_ddl('$jtr','$qtr') FROM dual;
spool off;
set define off;
@/var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$1;


connect $OPTWU/$PWDOPTWU@optwu

spool /home/jenkins/DBObjects_backup/WE_Objects/bkpUAT_`date +%d%b%y`_$qtr.sql;
SELECT dbms_metadata.get_ddl('$jtr','$qtr') FROM dual;
spool off;
set define off;
@/var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$1;


connect $OPTCU/$PWDOPTCU@optcu


spool /home/jenkins/DBObjects_backup/CEEMEA_Objects/bkpUAT_`date +%d%b%y`_$qtr.sql;
SELECT dbms_metadata.get_ddl('$jtr','$qtr') FROM dual;
spool off;
set define off;
@/var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$1;


connect $OPTLU/$PWDOPTLU@optlu

spool /home/jenkins/DBObjects_backup/LA_Objects/bkpUAT_`date +%d%b%y`_$qtr.sql;
SELECT dbms_metadata.get_ddl('$jtr','$qtr') FROM dual;
spool off;
set define off;
@/var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$1;

quit;
EOF
}


#===processing the changed files in a loop===#
for i in $var;do
echo "i = $i"
IP_Address="137.179.26.7"
subdir=`echo $i | rev | cut -f2- -d"/"| rev`
echo $subdir
str=`echo $i | awk -F"/"  '{print $NF}'`
echo $str
#ptr=`echo "$str" | cut -f 1 -d '.'`
#echo $ptr
#ktr=`echo $subdir | awk -F"/"  '{print $NF}'`
#echo $ktr

#######=============LINUX DEPLOYMENT - Inner Scripts===========##########
#Linux - 'R11' files deployment(If the file modified is from 'inner' then deploy to 'R11' in Optima Tx UAT)
if [ "X$subdir" = "XLinux/scripts/inner" ];then
# sebl*.sh files validation
#if  [ "X${str:0:4}" = "Xsebl" -a "X${str: -3}" = "X.sh" ] ;then
rsync --backup /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i $IP_Address:/var/opt/sebl/scripts/R11
ssh $IP_Address mv /var/opt/sebl/scripts/R11/$str~ /home/jenkins/Backup_Objects_Jenkins_Linux/bkp_`date +%d%b%y_%H:%M`_$str
ssh $IP_Address chmod 770 /home/jenkins/Backup_Objects_Jenkins_Linux/bkp_`date +%d%b%y_%H:%M`_$str /var/opt/sebl/scripts/R11/$str
ssh $IP_Address chgrp SEBLIOA /home/jenkins/Backup_Objects_Jenkins_Linux/bkp_`date +%d%b%y_%H:%M`_$str /var/opt/sebl/scripts/R11/$str 
echo "$i copied to bdlg3497:/var/opt/sebl/scripts/R11 successfully"
#else
#echo "This is not sebl*.sh file"
#fi 
#end file extension check
fi
#End Linux file deployment to R11 folder in Optima Tx Non-prod server


#######=============LINUX DEPLOYMENT - Generic Control Files ===========##########
#Linux - 'generic_ctl' files deployment(If the file modified is from 'ctl' deploy to 'generic_ctl' in Optima Tx UAT)
if [ "X$subdir" = "XLinux/ctl/generic_ctl" ];then
rsync --backup /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i $IP_Address:/var/opt/sebl/optima/R11/ctl/generic_ctl
ssh $IP_Address mv /var/opt/sebl/optima/R11/ctl/generic_ctl/$str~ /home/jenkins/Backup_Objects_Jenkins_Linux/bkp_`date +%d%b%y_%H:%M`_$str
ssh $IP_Address chmod 770 /var/opt/sebl/optima/R11/ctl/generic_ctl/$str /home/jenkins/Backup_Objects_Jenkins_Linux/bkp_`date +%d%b%y_%H:%M`_$str
ssh $IP_Address chgrp SEBLIOA /var/opt/sebl/optima/R11/ctl/generic_ctl/$str /home/jenkins/Backup_Objects_Jenkins_Linux/bkp_`date +%d%b%y_%H:%M`_$str
echo "$i copied to bdlg3497:/var/opt/sebl/scripts/R11/ctl/generic_ctl successfully"
fi
#End Linux file deployment to generic_ctl folder in Optima Tx Non-prod server


####=============LINUX DEPLOYMENT - Outer Scripts==============##########
#Linux - 'Scripts' files deployment(If the file modified is from 'Outer' then deploy to 'Scripts' in Optima Tx UAT)
if [ "X$subdir" = "XLinux/scripts/outer" ];then
#file extension sebl*.sh validation
#if  [ "X${str:0:4}" = "Xsebl" -a "X${str: -3}" = "X.sh" ] ;then
rsync --backup /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i $IP_Address:/var/opt/sebl/scripts
ssh $IP_Address mv /var/opt/sebl/scripts/$str~ /home/jenkins/Backup_Objects_Jenkins_Linux/bkp_`date +%d%b%y_%H:%M`_$str
ssh $IP_Address chmod 770 /home/jenkins/Backup_Objects_Jenkins_Linux/bkp_`date +%d%b%y_%H:%M`_$str /var/opt/sebl/scripts/$str
ssh $IP_Address chgrp SEBLIOA /home/jenkins/Backup_Objects_Jenkins_Linux/bkp_`date +%d%b%y_%H:%M`_$str /var/opt/sebl/scripts/$str
echo "$i copied to bdlg3497:/var/opt/sebl/scripts successfully"
#else
#echo "This is not sebl*.sh file"
#fi
#End file extension validation and deployment complete  
fi
#End Linux file deployment to R11 folder in Optima Tx non-prod server




####=============LINUX DEPLOYMENT - SETENV ==============##########
#Linux - 'ENV' files deployment(If the file modified is from 'SETENV' then deploy to 'Scripts' in Optima Tx UAT)
if [ "X$subdir" = "XLinux/scripts/regional_set_env/SETENV_UAT" ];then
#file extension sebl*.sh validation
#if  [ "X${str:0:13}" = "Xoptima_setenv" -a "X${str: -3}" = "X.sh" ] ;then
rsync --backup /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i $IP_Address:/var/opt/sebl/scripts
ssh $IP_Address mv /var/opt/sebl/scripts/$str~ /home/jenkins/Backup_Objects_Jenkins_Linux/bkp_`date +%d%b%y_%H:%M`_$str
ssh $IP_Address chmod 770 /home/jenkins/Backup_Objects_Jenkins_Linux/bkp_`date +%d%b%y_%H:%M`_$str /var/opt/sebl/scripts/$str
ssh $IP_Address chgrp SEBLIOA /home/jenkins/Backup_Objects_Jenkins_Linux/bkp_`date +%d%b%y_%H:%M`_$str /var/opt/sebl/scripts/$str
echo "$i copied to bdlg3497:/var/opt/sebl/scripts successfully"
#else
#echo "This is not sebl*.sh file"
#fi
#End file extension validation and deployment complete  
fi
#End Linux file deployment to R11 folder in Optima Tx non-prod server



######==========WINDOWS DEPLOYMENT '.bat' files=========########
#Windows - '.bat' files deployment(If the file modified is from 'Scripts')
if [ "X$subdir" = "XWindows/Interface/sebl/scripts" ];then
#file extension sebl*.bat validation
#if  [ "X${str:0:4}" = "Xsebl" -a "X${str: -4}" = "X.bat" ] ;then

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL212_scripts
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL212_scripts/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL212_scripts/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL214_scripts
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL214_scripts/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL214_scripts/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL216_scripts
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL216_scripts/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL216_scripts/$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL218_scripts
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL218_scripts/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str 
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL218_scripts/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
echo "$i copied to all Optima EIM servers to G:/apps/Siebel/scripts successfully"
#else
#echo "This is not sebl*.bat file"
#fi
#End file extension validation and deployment complete
fi
#End Windows file deployment to Scripts folder in Optima Tx non-prod server



####=======WINDOWS DEPLOYMENT(Anaplan_Scripts)=======######
#Windows -  files deployment(If the file modified is from 'Anaplan')
if [ "X$subdir" = "XWindows/Interface/Anaplan/sebl/scripts" ];then
####file extension check
#if  [ "X${str:0:4}" = "Xsebl" -a "X${str: -4}" = "X.bat" ] ;then
cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL219_scripts
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL219_scripts/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL219_scripts/$str
echo "$i copied to BDC-SIEBEL119:G:/apps/sebl/scripts successfully"
#else
#echo "This is not sebl*.bat file"
#fi
#End file extension validation and deployment complete
fi
#End Windows file deployment to Scripts folder in Optima Tx non-prod server



####========WINDOWS DEPLOYMENT(Anaplan)=======######
#Windows -  files deployment(If the file modified is from 'Anaplan')
if [ "X$subdir" = "XWindows/Interface/Anaplan/anaplan-connect-1-3-3-0" ];then
cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL219_anaplan-connect-1-3-3-0
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL219_anaplan-connect-1-3-3-0/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL219_anaplan-connect-1-3-3-0/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
echo "$i copied to bdc-siebel219:G:/apps/Anaplan/anaplan-connect-1-3-3-0 successfully"
fi
#End Windows file deployment to Scripts folder in Optima Tx non-prod server

####========WINDOWS DEPLOYMENT(Anaplan- Parameters)=======######
#Windows -  files deployment(If the file modified is from 'Anaplan')
if [ "X$subdir" = "XWindows/Interface/Anaplan/AnaplanMasterParam/AnaplanMasterParam_UAT" ];then
cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL219_anaplan-connect-1-3-3-0
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL219_anaplan-connect-1-3-3-0/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL219_anaplan-connect-1-3-3-0/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
echo "$i copied to bdc-siebel219:G:/apps/Anaplan/anaplan-connect-1-3-3-0 successfully"
fi
#End Windows file deployment to Scripts folder in Optima Tx non-prod server



#####=========WINDOWS DEPLOYMENT(.ifb)=========########
#Windows - '.ifb' files deployment(If the file modified is from 'ADMIN')
if [ "X$subdir" = "XWindows/Siebel/siebsrvr/ADMIN" ];then
#file extension sebl*.ifb validation
#if  [ "X${str: -4}" = "X.ifb" ] ;then
cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL212_ADMIN
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL212_ADMIN/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL212_ADMIN/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL214_ADMIN
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL214_ADMIN/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL214_ADMIN/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL216_ADMIN
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL216_ADMIN/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL216_ADMIN/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL218_ADMIN
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL218_ADMIN/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL218_ADMIN/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

echo "$i copied to all Optima EIM servers to G:/apps/Siebel/ses/siebsrvr/ADMIN successfully"
#else
#echo "This is not *.ifb file"
#fi
#End file extension validation and deployment complete
fi
#End Windows file deployment to Scripts folder in Optima Tx Non-prod server

####========WINDOWS DEPLOYMENT - APAC Parameters =======######
#Windows -  files deployment(If the file modified is from 'Parameters')
if [ "X$subdir" = "XWindows/Interface/sebl/Parameters/UAT/APAC" ];then
#file extension *.bat validation
#if  [ "X${str: -4}" = "X.bat" ] ;then
cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL216_APAC_Parameters
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL216_APAC_Parameters/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL216_APAC_Parameters/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
echo "$i copied to BDC-SIEBEL216:G:/apps/Parameters successfully"
#else
#echo "This is not *.bat file"
#fi
#End file extension validation and deployment complete
fi
#End Windows file deployment to Scripts folder in Optima Tx non-prod server


####========WINDOWS DEPLOYMENT - CE Parameters =======######
#Windows -  files deployment(If the file modified is from 'Parameters')
if [ "X$subdir" = "XWindows/Interface/sebl/Parameters/UAT/CEEMEA" ];then
#file extension *.bat validation
#if  [ "X${str: -4}" = "X.bat" ] ;then
cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL214_CE_Parameters
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL214_CE_Parameters/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL214_CE_Parameters/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
echo "$i copied to BDCSIEBEL214:G:/apps/Parameters successfully"
#else
#echo "This is not *.bat file"
#fi
#End file extension validation and deployment complete
fi
#End Windows file deployment to Scripts folder in Optima Tx non-prod server

####========WINDOWS DEPLOYMENT - LA Parameters =======######
#Windows -  files deployment(If the file modified is from 'Parameters')
if [ "X$subdir" = "XWindows/Interface/sebl/Parameters/UAT/NALA" ];then
#file extension *.bat validation
#if  [ "X${str: -4}" = "X.bat" ] ;then
cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL212_LA_Parameters
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL212_LA_Parameters/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL212_LA_Parameters/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
echo "$i copied to BDCSIEBEL212:G:/apps/Parameters successfully"
#else
#echo "This is not *.bat file"
#fi
#End file extension validation and deployment complete
fi
#End Windows file deployment to Scripts folder in Optima Tx non-prod server


####========WINDOWS DEPLOYMENT - WE Parameters =======######
#Windows -  files deployment(If the file modified is from 'Parameters')
if [ "X$subdir" = "XWindows/Interface/sebl/Parameters/UAT/WE" ];then
#file extension *.bat validation
#if  [ "X${str: -4}" = "X.bat" ] ;then
cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL218_WE_Parameters
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL218_WE_Parameters/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL218_WE_Parameters/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
echo "$i copied to BDCSIEBEL218:G:/apps/Parameters successfully"
#else
#echo "This is not *.bat file"
#fi
#End file extension validation and deployment complete.
fi
#End Windows file deployment to Scripts folder in Optima Tx non-prod server.

####========WINDOWS DEPLOYMENT - EXTERNAL Parameters =======######
#Windows -  files deployment(If the file modified is from 'Parameters')
if [ "X$subdir" = "XWindows/Interface/sebl/Parameters/UAT/External" ];then
#file extension *.bat validation
#if  [ "X${str: -4}" = "X.bat" ] ;then
cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL219_EXT_Parameters
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL219_EXT_Parameters/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL219_EXT_Parameters/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
echo "$i copied to BDCSIEBEL219:G:/apps/Parameters successfully"
#else
#echo "This is not *.bat file"
#fi
#End file extension validation and deployment complete.
fi
#End Windows file deployment to Scripts folder in Optima Tx non-prod server.

#####=========WINDOWS DEPLOYMENT(.ifb)=========########
#Windows - '.ifb' files deployment(If the file modified is from 'ADMIN_SCHEMA')
if [ "X$subdir" = "XWindows/Siebel/siebsrvr/ADMIN/ADMIN_SCHEMA" ];then
#file extension *.ifb validation
#if  [ "X${str: -4}" = "X.ifb" ] ;then
cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL212_ADMIN_SCHEMA
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL212_ADMIN_SCHEMA/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL212_ADMIN_SCHEMA/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL214_ADMIN_SCHEMA
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL214_ADMIN_SCHEMA/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL214_ADMIN_SCHEMA/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL216_ADMIN_SCHEMA
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL216_ADMIN_SCHEMA/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL216_ADMIN_SCHEMA/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL218_ADMIN_SCHEMA
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL218_ADMIN_SCHEMA/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL218_ADMIN_SCHEMA/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

echo "$i copied to all Optima EIM servers to G:/apps/Siebel/ses/siebsrvr/ADMIN/ADMIN_SCHEMA successfully"
#else
#echo "This is not *.ifb file"
#fi
#End file extension validation and deployment complete
fi
#End Windows file deployment to Scripts folder in Optima Tx Non-prod server


#####=========WINDOWS DEPLOYMENT - Siebel FS1 =========########
#Windows - Siebel FS files deployment(If the file modified is from 'customfiles')
if [ "X$subdir" = "XSIEBEL/SiebelFileSystem/custom_files" ];then

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL211_custom_files
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL211_custom_files/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL211_custom_files/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL213_custom_files
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL213_custom_files/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL213_custom_files/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL215_custom_files
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL215_custom_files/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL215_custom_files/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL217_custom_files
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL217_custom_files/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL217_custom_files/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

echo "$i copied to all Optima App servers successfully"

fi
#End Windows file deployment to Scripts folder in Optima Tx Non-prod server


#####=========WINDOWS DEPLOYMENT - Siebel FS2 =========########
#Windows - Siebel FS files deployment(If the file modified is from 'customfiles')
if [ "X$subdir" = "XSIEBEL/SiebelFileSystem/custom_images" ];then

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL211_custom_images
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL211_custom_images/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL211_custom_images/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL213_custom_images
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL213_custom_images/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL213_custom_images/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL215_custom_images
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL215_custom_images/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL215_custom_images/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL217_custom_images
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL217_custom_images/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL217_custom_images/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

echo "$i copied to all Optima App servers successfully"

fi
#End Windows file deployment to Scripts folder in Optima Tx Non-prod server


#####=========WINDOWS DEPLOYMENT - Siebel FS3 =========########
#Windows - Siebel FS files deployment(If the file modified is from 'customfiles')
if [ "X$subdir" = "XSIEBEL/SiebelFileSystem/custom_scripts" ];then

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL211_custom_scripts
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL211_custom_scripts/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL211_custom_scripts/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL213_custom_scripts
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL213_custom_scripts/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL213_custom_scripts/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL215_custom_scripts
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL215_custom_scripts/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL215_custom_scripts/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

cp -b /var/lib/jenkins/workspace/OptimaTX_Objects_Migration_UAT/$i /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL217_custom_scripts
mv /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL217_custom_scripts/$str~ /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str
unix2dos /home/jenkins/PG_Jenkins_scripts_Migration_UAT/BDCSIEBEL217_custom_scripts/$str
unix2dos /home/jenkins/Backup_Objects_Jenkins_Win/bkp_`date +%d%b%y_%H%M`_$str

echo "$i copied to all Optima App servers successfully"

fi
#End Windows file deployment to Scripts folder in Optima Tx Non-prod server



export ORACLE_HOME=/opt/oracle/product/12.2_64bitclient
export PATH=$ORACLE_HOME/bin:$PATH


#if [ "X$subdir" = "XPLSQL/OPTDEV/SIEB2018/TABLE" ];then 
#export a="$a $i"
#fi

if [ "X$subdir" = "XPLSQL/OPTDEV/SIEB2018/VIEW" ];then
export b="$b $i"
fi

if [ "X$subdir" = "XPLSQL/OPTDEV/SIEB2018/MATERIALIZED_VIEW" ];then
export c="$c $i"
fi

if [ "X$subdir" = "XPLSQL/OPTDEV/SIEB2018/PROCEDURE" ];then 
export d="$d $i"
fi

if [ "X$subdir" = "XPLSQL/OPTDEV/SIEB2018/FUNCTION" ];then
export e="$e $i"
fi

if [ "X$subdir" = "XPLSQL/OPTDEV/SIEB2018/PACKAGE" ];then
export f="$f $i"
fi

if [ "X$subdir" = "XPLSQL/OPTDEV/SIEB2018/PACKAGE_BODY" ];then 
export g="$g $i"
fi

if [ "X$subdir" = "XPLSQL/OPTDEV/SIEB2018/TRIGGER" ];then
export h="$h $i"
fi

#if [ "X$subdir" = "XPLSQL/OPTDEV/SIEB2018/SYNONYM" ];then
#export j="$j $i"
#fi
done


#===processing DB objects separately to run in mentioned sequence below==#
for x in $b $c $d $e $f $g $h ;do
echo "$x is going to get compiled now"
dir=`echo $x | rev | cut -f2- -d"/"| rev`
echo $dir
etr=`echo $x | awk -F"/"  '{print $NF}'`
echo $etr
qtr=`echo "$etr" | cut -f 1 -d '.'`
echo $qtr
jtr=`echo $dir | awk -F"/"  '{print $NF}'`
echo $jtr
DBObjectscompile $x
done



###==========Error handling for last commit=======####
echo $int
if grep 'ERROR:\|error:' $int; then
echo "Build failed"
else
echo $(git rev-parse HEAD) >/home/jenkins/Last_Commit_SHA_UAT
fi
